### PR TITLE
Compile time reduction and cmake test support

### PR DESCRIPTION
**Pull request by offa**
Notable compile time reduction of the tests by compiling the expensive test main only once.

Improved test handling and CTest support.

### CODE REVIEW

**Comment by offa** [comment]
> Perhaps I'm just being overly paranoid, but if using this approach I'd rather see separate test_main11, test_main14 and test_main17 helper libraries -- although doing this would probably make compile times slower rather than faster!

At the moment this would safe a single compilation only; `test_contract_checking` can use one already compiled, either C++11, 14 or 17.


> It often works, but can sometimes lead to strange ABI problems and ODR violations as different files "see" different implementations of standard library functions.

At least for GCC and Clang it should be ABI stable.

**Comment by offa** [comment]
@tcbrindle if this makes sense to you, I can move the CTest part to a separate PR.

**Comment by offa** [comment]
@tcbrindle any news on this?

**Comment by tcbrindle** [comment]
Hi, I've changed the CMake setup for this repo quite dramatically in order to more easily support CI testing. It no longer tries to compile three different test executables in one project -- instead, it's up to the user to select the C++ version for tests at CMake configure time. This means that Catch is only built once.

The changes also enable testing with CTest, thanks for the suggestion!

**Comment by offa** [comment]
Great! :smile:

**Pull request closed without merging**
